# Generated by Django 3.2.15 on 2022-10-12 19:20

from django.db import migrations, models
import weather.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=35, verbose_name=weather.models.City),
        ),
    ]
