# Generated by Django 3.2.15 on 2022-11-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_city_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='url',
            field=models.SlugField(max_length=130),
        ),
    ]
