# Generated by Django 3.2.15 on 2022-11-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_alter_city_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='url',
        ),
    ]
