# Generated by Django 3.2.15 on 2022-11-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_city_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='url',
            new_name='slug',
        ),
    ]
