# Generated by Django 3.2.15 on 2022-11-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_rename_url_city_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='slug',
            new_name='url',
        ),
    ]
